apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-j64n
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-j64n
    app.kubernetes.io/part-of: cin4s-839-0094-app
  name: devfile-sample-j64n
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-j64n
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-j64n
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0094-tenant/cin4s-839-0094-app/devfile-sample-j64n@sha256:5e1144fe08cad06efdf92cc52797584ff9cba34d5d6df5a1baa05ccf7f40b3b6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
